DTStack/dt-utils

docs/utils.md
src/utils.ts
test/utils.test.ts

1、迁移资产的isObj到utils.ts
2、增加isObj单测
3、增加文档说明
关联issue：#20

Feat migrate is obj

---

docs/utils.md
src/utils.ts
test/utils.test.ts

1、迁移资产的isEmpty到utils.ts
2、增加isEmpty单测
3、增加文档说明
关联issue：#20

Feat migrate is empty

---

docs/utils.md
src/utils.ts
test/utils.test.ts

1、迁移资产的transformArray到utils.ts
2、增加transformArray单测
3、增加文档说明
关联issue：#20

Feat migrate transform array

---

docs/utils.md
src/utils.ts
test/utils.test.ts

1、迁移资产的removeEmpty到utils.ts
2、增加removeEmpty单测
3、增加文档说明
关联issue：#20

Feat migrate remove empty

---

docs/utils.md
src/utils.ts

feat: add transformArray ts

---

src/indexedDB.ts

优化 indexedDB，添加开关，控制 indexedDB 每次 get、set 是否打印 log

refactor: optimize indexedDB log

---

src/utils.ts

与 issue #25 相同的问题
shouldRender 的 this 指向导致报错

fix: replace this

---

docs/utils.md
src/utils.ts

refactor: remove appinfo

---

docs/utils.md
src/utils.ts
test/utils.test.ts

WIP: feat: add getThousandth to utils

---

docs/utils.md
src/utils.ts

- 增加`base64`相关方法
- 增加 `isUtf8` 用于判断是否是`utf-8`
- 增加 `utf16to8`  转化为`utf-8`
- 增加 `base64Encode` 将字符串进行`base64`处理

feat: add three Base64 related methods

---

src/utils.ts
test/utils.test.ts

- 优化千分位
- 千分位支持传入 undefined、null，此时返回 '0'

feat: improve utils getThousandth

---

docs/utils.md
src/utils.ts
test/utils.test.ts

- 优化千分位
- 优化了千分位的写法
- 移除了 toQfw 方法

feat: improve getThousandth and remove toQfw

---

docs/utils.md

- `mergeDeep`方法文档使用方式不对
- 更改`mergeDeep`方法文档

docs: modified mergeDeep md

---

docs/ldb.md
src/localDB.ts
test/localDB.test.ts

feat: #64 localDB add remove function

---

docs/utils.md
src/utils.ts
test/utils.test.ts
yarn.lock

getThousandth 传入空字符时也可以显示 0，标签中有较多该场景

feat: getThousandth get '' return '0'

---

.github/workflows/CI.yml

ci: github action

---

src/cookie.ts

fix: cookie ts type completion

---

src/utils.ts

fix(#80):  example Change the edge matching rule of the browser to edg

---

docs/ldb.md
src/localDB.ts
test/localDB.test.ts

fix: #82 optimize localStorage's get and set function

---

docs/utils.md
package.json
src/cookie.ts
src/utils.ts
test/cookie.test.ts
test/utils.test.ts
yarn.lock

feat(utils): add getUrlPathname and getUrlQueryParams for router

---

src/utils.ts
test/utils.test.ts

fix: #92 optimize getQueryParameters's return

---

tsconfig.json

fix: add DOM.Iterable lib in tsconfig

---

package.json

fix: #95 sideEffects should be boolean false
